export const CADASTRO_PEDIDO_SUCESSO = 'CADASTRO_PEDIDO_SUCESSO';
export const CARREGAR_PEDIDOS_SUCESSO = 'CARREGAR_PEDIDOS_SUCESSO';
export const FINALIZAR_PEDIDO_SUCESSO = 'FINALIZAR_PEDIDO_SUCESSO';